import Header from "@/components/Header";
import PrivateLayout from "@/layouts/PaivateLayout";
import React from "react";

export const metadata = {
  title: "IT Hub Visa Token",
  description: "Generated by create next app",
};

const ProcessLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <PrivateLayout>
      <Header />
      {children}
    </PrivateLayout>
  );
};

export default ProcessLayout;
