import Header from "@/components/Header";
import { Box } from "@mui/material";
import React from "react";

export const metadata = {
  title: "IT Hub Visa Token",
  description: "Generated by create next app",
};

const ProcessLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Box>
      <Header />
      {children}
    </Box>
  );
};

export default ProcessLayout;
