import React from "react";

export const metadata = {
  title: "Create | Agents | IT Hub",
  description: "Generated by create next app",
};

const AgentsLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default AgentsLayout;
