import { Box } from "@mui/material";
import React from "react";

export const metadata = {
  title: "Login | IT Hub Visa Token",
  description: "Generated by create next app",
};

const LoginLayout = ({ children }: { children: React.ReactNode }) => {
  return <Box>{children}</Box>;
};

export default LoginLayout;
