import React from "react";

export const metadata = {
  title: "Applications | IT Hub",
  description: "Generated by create next app",
};

const ApplicationLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default ApplicationLayout;
