import { Box } from "@mui/material";
import React from "react";

export const metadata = {
  title: "Ongoing Applications | IT Hub",
  description: "Generated by create next app",
};

const OngoingApplicationsLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return <Box>{children}</Box>;
};

export default OngoingApplicationsLayout;
